### ISSUE TITLE
Installing from source gives UnicodeDecodeError

### ISSUE THREAD

**Issue by AbdealiJK** [sybrenstuvel/python-rsa#129] opened 2019-05-13 09:18 UTC
When I install `rsa` with source, it fails with an ascii codec error.
It works if I install it with the wheel.

##### Environment Versions

1. OS Type `CentOS 7`
1. Python version: `Python 3.6.6`
1. pip version: `pip 8.1.2 from /usr/lib/python3.6/site-packages (python 3.6)`

##### Steps to replicate

```
$ docker run -it --rm centos:7 bash
# yum install -y epel-release
...
# yum install -y python36-pip
...
# pip3.6 install --no-binary :all: rsa
Collecting rsa
  Downloading https://files.pythonhosted.org/packages/cb/d0/8f99b91432a60ca4b1cd478fd0bdf28c1901c58e3a9f14f4ba3dba86b57f/rsa-4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oh4v54vc/rsa/setup.py", line 20, in <module>
        long_description = f.read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 898: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oh4v54vc/rsa/
You are using pip version 8.1.2, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by simonvanderveldt** [comment] 2019-06-25 08:04
Seems like there's something wrong with the readme?
https://github.com/NixOS/nixpkgs/issues/53116

**Comment by sybrenstuvel** [comment] 2019-06-26 09:06
Please test with the latest revision of the `master` branch, it should be fixed now. If you can confirm it's fixed, I can release it.

**Comment by thusoy** [comment] 2019-07-15 22:08
I can confirm that the problem is fixed on master for me at least.

**Comment by sybrenstuvel** [comment] 2019-08-04 14:41
Thanks for checking. I'm preparing version 4.1 for release soon.

**Closed by sybrenstuvel** 2019-08-04 14:41 UTC

**Comment by AbdealiJK** [comment] 2020-02-11 10:59
Any update for the release ?
